{
  "name": "await-call",
  "version": "0.0.0",
  "description": "Async await wrapper for easy error handling without try-catch",
  "main": "index.js",
  "directories": {
    "example": "example"
  },
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/song940/await-call.git"
  },
  "author": "Lsong",
  "license": "MIT",
  "bugs": {
    "url": "https://github.com/song940/await-call/issues"
  },
  "homepage": "https://github.com/song940/await-call#readme",
  "keywords": [
    "async",
    "await",
    "call",
    "error",
    "try-catch"
  ]
}
